USE coffee_shop;

/*
===============================================================================
                            COFFEE SHOP SALES ANALYSIS
===============================================================================

DESCRIPTION:
This project analyzes Coffee Shop sales data using MySQL to answer
real-world business questions and generate actionable business insights.

OBJECTIVES:
• Analyze overall revenue performance
• Evaluate sales trends
• Identify top-performing products
• Compare store performance
• Generate business insights for decision-making

SQL CONCEPTS USED:
• SELECT
• WHERE
• GROUP BY
• ORDER BY
• INNER JOIN
• Aggregate Functions
• HAVING
• Date Functions
• CASE Statements
• Subqueries

DATABASE:
coffee_shop

AUTHOR:
Tanmay Chavan

===============================================================================
*/

-- =============================================================================
-- Preview Tables
-- =============================================================================

SELECT *
FROM products;

SELECT *
FROM stores;

SELECT *
FROM transactions;





/*==============================================================================
SECTION 1 : REVENUE ANALYSIS

Objective:
Analyze revenue generated by the coffee shop and identify the
highest revenue-generating products, categories and store locations.
==============================================================================*/


/*
Business Question 1:
What is the total revenue generated?

Purpose:
Calculate the total sales revenue generated by the coffee shop.
*/

SELECT
    ROUND(SUM(t.transaction_qty * p.unit_price), 2) AS Total_Revenue
FROM transactions t
JOIN products p
    ON t.product_id = p.product_id;



/*
Business Question 2:
What is the average order value?

Purpose:
Calculate the average value of each customer transaction.
*/

SELECT
    ROUND(AVG(t.transaction_qty * p.unit_price), 2) AS Average_Order_Value
FROM transactions t
JOIN products p
    ON t.product_id = p.product_id;



/*
Business Question 3:
Which product generated the highest revenue?

Purpose:
Identify the product contributing the highest revenue.
*/

SELECT
    p.product_detail,
    ROUND(SUM(t.transaction_qty * p.unit_price), 2) AS Revenue
FROM transactions t
JOIN products p
    ON t.product_id = p.product_id
GROUP BY
    p.product_detail
ORDER BY
    Revenue DESC;



/*
Business Question 4:
How much revenue was generated by each product category?

Purpose:
Compare revenue generated across product categories.
*/

SELECT
    p.product_category,
    ROUND(SUM(t.transaction_qty * p.unit_price), 2) AS Revenue
FROM transactions t
JOIN products p
    ON t.product_id = p.product_id
GROUP BY
    p.product_category
ORDER BY
    Revenue DESC;



/*
Business Question 5:
How much revenue was generated by each store location?

Purpose:
Compare revenue generated by each store.
*/

SELECT
    s.store_location,
    ROUND(SUM(t.transaction_qty * p.unit_price), 2) AS Revenue
FROM transactions t
JOIN stores s
    ON t.store_id = s.store_id
JOIN products p
    ON t.product_id = p.product_id
GROUP BY
    s.store_location
ORDER BY
    Revenue DESC;





/*==============================================================================
SECTION 2 : SALES ANALYSIS

Objective:
Analyze customer purchasing behaviour, product demand,
monthly trends and peak business hours.
==============================================================================*/


/*
Business Question 6:
Which product sold the highest quantity?

Purpose:
Identify the product with the highest sales volume.
*/

SELECT
    p.product_detail,
    SUM(t.transaction_qty) AS Total_Quantity_Sold
FROM transactions t
JOIN products p
    ON t.product_id = p.product_id
GROUP BY
    p.product_detail
ORDER BY
    Total_Quantity_Sold DESC;



/*
Business Question 7:
What are the Top 10 best-selling products?

Purpose:
Identify the products with the highest quantity sold.
*/

SELECT
    p.product_detail,
    SUM(t.transaction_qty) AS Total_Quantity_Sold
FROM transactions t
JOIN products p
    ON t.product_id = p.product_id
GROUP BY
    p.product_detail
ORDER BY
    Total_Quantity_Sold DESC
LIMIT 10;



/*
Business Question 8:
What are the Bottom 10 least-selling products?

Purpose:
Identify products with the lowest sales quantity.
*/

SELECT
    p.product_detail,
    SUM(t.transaction_qty) AS Total_Quantity_Sold
FROM transactions t
JOIN products p
    ON t.product_id = p.product_id
GROUP BY
    p.product_detail
ORDER BY
    Total_Quantity_Sold ASC
LIMIT 10;



/*
Business Question 9:
How many units were sold in each product category?

Purpose:
Compare sales volume across product categories.
*/

SELECT
    p.product_category,
    SUM(t.transaction_qty) AS Quantity_Sold
FROM transactions t
JOIN products p
    ON t.product_id = p.product_id
GROUP BY
    p.product_category
ORDER BY
    Quantity_Sold DESC;



/*
Business Question 10:
What is the average quantity sold per transaction?

Purpose:
Measure the average purchase quantity per order.
*/

SELECT
    ROUND(AVG(transaction_qty), 2) AS Average_Quantity
FROM transactions;



/*
Business Question 11:
Which month generated the highest revenue?

Purpose:
Identify the best-performing month based on revenue.
*/

SELECT
    MONTHNAME(transaction_date) AS Month,
    ROUND(SUM(t.transaction_qty * p.unit_price), 2) AS Revenue
FROM transactions t
JOIN products p
    ON t.product_id = p.product_id
GROUP BY
    MONTH(transaction_date),
    MONTHNAME(transaction_date)
ORDER BY
    Revenue DESC;



/*
Business Question 12:
Which day of the week generated the highest revenue?

Purpose:
Identify the busiest day based on revenue.
*/

SELECT
    DAYNAME(transaction_date) AS Day,
    ROUND(SUM(t.transaction_qty * p.unit_price), 2) AS Revenue
FROM transactions t
JOIN products p
    ON t.product_id = p.product_id
GROUP BY
    DAYNAME(transaction_date)
ORDER BY
    Revenue DESC;



/*
Business Question 13:
Which hour receives the highest number of transactions?

Purpose:
Identify peak business hours based on transaction count.
*/

SELECT
    HOUR(transaction_time) AS Hour,
    COUNT(transaction_id) AS Total_Transactions
FROM transactions
GROUP BY
    HOUR(transaction_time)
ORDER BY
    Total_Transactions DESC;



/*
Business Question 14:
How much revenue is generated during each hour?

Purpose:
Determine which hours contribute the most revenue.
*/

SELECT
    HOUR(transaction_time) AS Hour,
    ROUND(SUM(t.transaction_qty * p.unit_price), 2) AS Revenue
FROM transactions t
JOIN products p
    ON t.product_id = p.product_id
GROUP BY
    HOUR(transaction_time)
ORDER BY
    Revenue DESC;



/*
Business Question 15:
What is the average revenue generated each month?

Purpose:
Compare the average revenue generated across months.
*/

SELECT
    MONTHNAME(transaction_date) AS Month,
    ROUND(AVG(t.transaction_qty * p.unit_price), 2) AS Average_Revenue
FROM transactions t
JOIN products p
    ON t.product_id = p.product_id
GROUP BY
    MONTH(transaction_date),
    MONTHNAME(transaction_date)
ORDER BY
    MONTH(transaction_date);





/*==============================================================================
SECTION 3 : STORE ANALYSIS

Objective:
Compare store performance using revenue,
transaction volume and product sales.
==============================================================================*/


/*
Business Question 16:
Which store handled the highest number of transactions?

Purpose:
Identify the busiest store based on transaction count.
*/

SELECT
    s.store_location,
    COUNT(t.transaction_id) AS Total_Transactions
FROM transactions t
JOIN stores s
    ON t.store_id = s.store_id
GROUP BY
    s.store_location
ORDER BY
    Total_Transactions DESC;



/*
Business Question 17:
Which store sold the highest quantity of products?

Purpose:
Identify the store with the highest sales volume.
*/

SELECT
    s.store_location,
    SUM(t.transaction_qty) AS Total_Quantity_Sold
FROM transactions t
JOIN stores s
    ON t.store_id = s.store_id
GROUP BY
    s.store_location
ORDER BY
    Total_Quantity_Sold DESC;



/*
Business Question 18:
What is the average order value for each store?

Purpose:
Compare customer spending across different store locations.
*/

SELECT
    s.store_location,
    ROUND(AVG(t.transaction_qty * p.unit_price), 2) AS Average_Order_Value
FROM transactions t
JOIN stores s
    ON t.store_id = s.store_id
JOIN products p
    ON t.product_id = p.product_id
GROUP BY
    s.store_location
ORDER BY
    Average_Order_Value DESC;



/*
Business Question 19:
Which product category generated the highest revenue in each store?

Purpose:
Identify the best-performing category for every store.
*/

SELECT
    s.store_location,
    p.product_category,
    ROUND(SUM(t.transaction_qty * p.unit_price), 2) AS Revenue
FROM transactions t
JOIN stores s
    ON t.store_id = s.store_id
JOIN products p
    ON t.product_id = p.product_id
GROUP BY
    s.store_location,
    p.product_category
ORDER BY
    s.store_location,
    Revenue DESC;



/*
Business Question 20:
How much revenue was generated by each product in every store?

Purpose:
Analyze product-level revenue performance across stores.
*/

SELECT
    s.store_location,
    p.product_detail,
    ROUND(SUM(t.transaction_qty * p.unit_price), 2) AS Revenue
FROM transactions t
JOIN stores s
    ON t.store_id = s.store_id
JOIN products p
    ON t.product_id = p.product_id
GROUP BY
    s.store_location,
    p.product_detail
ORDER BY
    s.store_location,
    Revenue DESC;
    
/*==============================================================================
SECTION 4 : PRODUCT PERFORMANCE ANALYSIS

Objective:
Evaluate product performance by identifying high-performing
products, product categories and comparing revenue
against business benchmarks.
==============================================================================*/


/*
Business Question 21:
Which products generated more than ₹10,000 in revenue?

Purpose:
Identify products that contribute significantly
to the overall revenue.
*/

SELECT
    p.product_detail,
    ROUND(SUM(t.transaction_qty * p.unit_price), 2) AS Revenue
FROM transactions t
JOIN products p
    ON t.product_id = p.product_id
GROUP BY
    p.product_detail
HAVING
    Revenue > 10000
ORDER BY
    Revenue DESC;



/*
Business Question 22:
Which product categories generated more than ₹50,000 in revenue?

Purpose:
Identify high-performing product categories based on revenue.
*/

SELECT
    p.product_category,
    ROUND(SUM(t.transaction_qty * p.unit_price), 2) AS Revenue
FROM transactions t
JOIN products p
    ON t.product_id = p.product_id
GROUP BY
    p.product_category
HAVING
    Revenue > 50000
ORDER BY
    Revenue DESC;



/*
Business Question 23:
Which products were sold in more than 500 transactions?

Purpose:
Identify products with consistently high customer demand.
*/

SELECT
    p.product_detail,
    COUNT(t.transaction_id) AS Total_Transactions
FROM transactions t
JOIN products p
    ON t.product_id = p.product_id
GROUP BY
    p.product_detail
HAVING
    Total_Transactions > 500
ORDER BY
    Total_Transactions DESC;



/*
Business Question 24:
Which product categories sold more than 10,000 units?

Purpose:
Identify product categories with the highest sales volume.
*/

SELECT
    p.product_category,
    SUM(t.transaction_qty) AS Quantity_Sold
FROM transactions t
JOIN products p
    ON t.product_id = p.product_id
GROUP BY
    p.product_category
HAVING
    Quantity_Sold > 10000
ORDER BY
    Quantity_Sold DESC;



/*
Business Question 25:
Which products generated above-average revenue?

Purpose:
Compare each product's revenue against the
overall average product revenue.
*/

SELECT
    p.product_detail,
    ROUND(SUM(t.transaction_qty * p.unit_price), 2) AS Revenue
FROM transactions t
JOIN products p
    ON t.product_id = p.product_id
GROUP BY
    p.product_detail
HAVING
    Revenue >
(
    SELECT AVG(Product_Revenue)
    FROM
    (
        SELECT
            SUM(t.transaction_qty * p.unit_price) AS Product_Revenue
        FROM transactions t
        JOIN products p
            ON t.product_id = p.product_id
        GROUP BY
            p.product_detail
    ) AS AvgRevenue
)
ORDER BY
    Revenue DESC;





/*==============================================================================
SECTION 5 : BUSINESS INSIGHTS

Objective:
Generate actionable business insights by classifying
products, stores and customer orders using SQL.
==============================================================================*/


/*
Business Question 26:
Classify products based on total revenue.

Purpose:
Categorize products into High, Medium and Low performers
to support pricing and inventory decisions.
*/

SELECT
    p.product_detail,
    ROUND(SUM(t.transaction_qty * p.unit_price), 2) AS Revenue,
    CASE
        WHEN SUM(t.transaction_qty * p.unit_price) >= 50000
            THEN 'High Performer'
        WHEN SUM(t.transaction_qty * p.unit_price) >= 20000
            THEN 'Medium Performer'
        ELSE 'Low Performer'
    END AS Performance
FROM transactions t
JOIN products p
    ON t.product_id = p.product_id
GROUP BY
    p.product_detail
ORDER BY
    Revenue DESC;



/*
Business Question 27:
Classify stores based on revenue.

Purpose:
Evaluate overall store performance based on
total revenue generated.
*/

SELECT
    s.store_location,
    ROUND(SUM(t.transaction_qty * p.unit_price), 2) AS Revenue,
    CASE
        WHEN SUM(t.transaction_qty * p.unit_price) >= 150000
            THEN 'Excellent'
        WHEN SUM(t.transaction_qty * p.unit_price) >= 100000
            THEN 'Good'
        ELSE 'Needs Improvement'
    END AS Store_Performance
FROM transactions t
JOIN stores s
    ON t.store_id = s.store_id
JOIN products p
    ON t.product_id = p.product_id
GROUP BY
    s.store_location
ORDER BY
    Revenue DESC;



/*
Business Question 28:
Which transactions are considered Bulk Orders?

Purpose:
Identify transactions involving large purchase quantities.
*/

SELECT
    transaction_id,
    transaction_qty,
    CASE
        WHEN transaction_qty >= 5
            THEN 'Bulk Order'
        ELSE 'Regular Order'
    END AS Order_Type
FROM transactions;



/*
Business Question 29:
Which product categories contribute the highest revenue?

Purpose:
Compare the revenue contribution of each
product category.
*/

SELECT
    p.product_category,
    ROUND(SUM(t.transaction_qty * p.unit_price), 2) AS Revenue
FROM transactions t
JOIN products p
    ON t.product_id = p.product_id
GROUP BY
    p.product_category
ORDER BY
    Revenue DESC;



/*
Business Question 30:
Which products generated less than the average product revenue?

Purpose:
Identify underperforming products that may require
promotional or pricing strategies.
*/

SELECT
    p.product_detail,
    ROUND(SUM(t.transaction_qty * p.unit_price), 2) AS Revenue
FROM transactions t
JOIN products p
    ON t.product_id = p.product_id
GROUP BY
    p.product_detail
HAVING
    Revenue <
(
    SELECT AVG(Product_Revenue)
    FROM
    (
        SELECT
            SUM(t.transaction_qty * p.unit_price) AS Product_Revenue
        FROM transactions t
        JOIN products p
            ON t.product_id = p.product_id
        GROUP BY
            p.product_detail
    ) AS AvgRevenue
)
ORDER BY
    Revenue ASC;





/*==============================================================================
PROJECT SUMMARY

Key Business Insights Generated:

✓ Total Revenue Analysis
✓ Average Order Value
✓ Product Revenue Analysis
✓ Product Category Performance
✓ Store Performance Analysis
✓ Monthly Sales Trends
✓ Daily Sales Trends
✓ Peak Business Hours
✓ Product Sales Analysis
✓ Product Performance Classification
✓ Store Performance Classification
✓ Bulk Order Identification
✓ Above-Average Product Analysis
✓ Underperforming Product Analysis

SQL Concepts Demonstrated:

✓ SELECT
✓ INNER JOIN
✓ Aggregate Functions (SUM, AVG, COUNT)
✓ GROUP BY
✓ ORDER BY
✓ HAVING
✓ CASE Statements
✓ Subqueries
✓ Date Functions
✓ LIMIT
✓ Business-Oriented SQL Analysis

Project Completed Successfully.

==============================================================================*/